### ISSUE TITLE
Infinite loop on exit 

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/crush-shell#1]
Infinite loop 
https://github.com/contour-terminal/crush-shell/blob/8c6a2e4f9e9a8e877051bac9818589d66d1ce6ba/src/CoreVM/vm/Runner.cpp#L27-L30

its called on exit here :
https://github.com/contour-terminal/crush-shell/blob/8c6a2e4f9e9a8e877051bac9818589d66d1ce6ba/src/CoreVM/vm/Runner.cpp#L898-L902

**Comment by christianparpart** [comment]
lol that must be a brain damage bug. wow. thanks :)

**Comment by christianparpart** [comment]
Fixed in b263188bf769181e5248ed901c6b28025a7a9fb7. Thx. :)
